#!/usr/bin/env bash
set -Eeuo pipefail

SERVICE_NAME="mihomo.service"

log() {
  printf '[tun] %s\n' "$*"
}

die() {
  printf '[tun] ERROR: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  bash advanced/client-tun.sh enable
  bash advanced/client-tun.sh disable
  bash advanced/client-tun.sh status
  bash advanced/client-tun.sh help

This is an optional experimental helper. It toggles tun.enable in the
mihomo config generated by ../client.sh and grants cap_net_admin to the
mihomo binary when enabling TUN mode.
EOF
}

detect_target_user() {
  if [ "$(id -u)" -eq 0 ] && [ -n "${SUDO_USER:-}" ]; then
    printf '%s' "$SUDO_USER"
  else
    id -un
  fi
}

detect_target_home() {
  local target_user="$1"
  local home_dir=""

  home_dir="$(getent passwd "$target_user" | cut -d: -f6)"
  [ -n "$home_dir" ] || die "无法找到用户 ${target_user} 的 HOME。"
  printf '%s' "$home_dir"
}

detect_target_config_home() {
  local config_home="${XDG_CONFIG_HOME:-}"

  if [ -n "$config_home" ]; then
    case "$config_home" in
      /*) printf '%s' "$config_home" ;;
      *) die "XDG_CONFIG_HOME 必须是绝对路径: ${config_home}" ;;
    esac
  else
    printf '%s/.config' "$TARGET_HOME"
  fi
}

TARGET_USER="$(detect_target_user)"
TARGET_HOME="$(detect_target_home "$TARGET_USER")"
TARGET_UID="$(id -u "$TARGET_USER")"
CONFIG_HOME="$(detect_target_config_home)"
MIHOMO_CONFIG_FILE="${CONFIG_HOME}/mihomo/config.yaml"
MIHOMO_BIN="${TARGET_HOME}/.local/bin/mihomo"

backup_config() {
  local backup_file

  [ -f "$MIHOMO_CONFIG_FILE" ] || die "未找到 mihomo 配置: ${MIHOMO_CONFIG_FILE}。请先运行 bash client.sh install。"
  backup_file="${MIHOMO_CONFIG_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$MIHOMO_CONFIG_FILE" "$backup_file"
  if [ "$(id -u)" -eq 0 ]; then
    chown "$TARGET_USER:$TARGET_USER" "$backup_file"
  fi
  log "已备份配置: ${backup_file}"
}

ensure_tun_block() {
  if grep -q '^tun:[[:space:]]*$' "$MIHOMO_CONFIG_FILE"; then
    return
  fi

  cat >> "$MIHOMO_CONFIG_FILE" <<'EOF'

tun:
  enable: false
  stack: system
  auto-route: true
  auto-detect-interface: true
  strict-route: false
  dns-hijack:
    - any:53
EOF

  if [ "$(id -u)" -eq 0 ]; then
    chown "$TARGET_USER:$TARGET_USER" "$MIHOMO_CONFIG_FILE"
  fi
}

set_tun_enabled() {
  local value="$1"
  local tmp_file

  ensure_tun_block
  tmp_file="$(mktemp)"

  awk -v value="$value" '
    BEGIN { in_tun = 0; changed = 0 }
    /^tun:[[:space:]]*$/ {
      in_tun = 1
      print
      next
    }
    in_tun && /^[^[:space:]#][^:]*:[[:space:]]*/ {
      if (!changed) {
        print "  enable: " value
        changed = 1
      }
      in_tun = 0
    }
    in_tun && /^[[:space:]]+enable:[[:space:]]*/ && !changed {
      print "  enable: " value
      changed = 1
      next
    }
    { print }
    END {
      if (in_tun && !changed) {
        print "  enable: " value
      }
    }
  ' "$MIHOMO_CONFIG_FILE" > "$tmp_file"

  cat "$tmp_file" > "$MIHOMO_CONFIG_FILE"
  rm -f "$tmp_file"

  if [ "$(id -u)" -eq 0 ]; then
    chown "$TARGET_USER:$TARGET_USER" "$MIHOMO_CONFIG_FILE"
  fi

  log "已设置 tun.enable=${value}"
}

grant_mihomo_capability() {
  [ -x "$MIHOMO_BIN" ] || die "未找到 mihomo 二进制: ${MIHOMO_BIN}。请先运行 bash client.sh install。"

  if ! command -v setcap >/dev/null 2>&1; then
    if command -v apt-get >/dev/null 2>&1; then
      log "缺少 setcap，自动安装 libcap2-bin。"
      if [ "$(id -u)" -eq 0 ]; then
        apt-get update
        apt-get install -y libcap2-bin
      else
        command -v sudo >/dev/null 2>&1 || die "缺少 setcap，且未找到 sudo。请先安装 libcap2-bin。"
        sudo apt-get update
        sudo apt-get install -y libcap2-bin
      fi
    else
      die "未找到 setcap。请先安装 libcap2-bin。"
    fi
  fi

  if [ "$(id -u)" -eq 0 ]; then
    setcap cap_net_admin,cap_net_bind_service+ep "$MIHOMO_BIN"
  else
    command -v sudo >/dev/null 2>&1 || die "启用 TUN 需要 setcap 权限，但未找到 sudo。"
    sudo setcap cap_net_admin,cap_net_bind_service+ep "$MIHOMO_BIN"
  fi

  log "已为 mihomo 授权 cap_net_admin,cap_net_bind_service。"
}

user_systemctl() {
  if [ "$(id -u)" -ne 0 ]; then
    systemctl --user "$@"
    return
  fi

  if [ -S "/run/user/${TARGET_UID}/bus" ]; then
    sudo -u "$TARGET_USER" env \
      XDG_RUNTIME_DIR="/run/user/${TARGET_UID}" \
      DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${TARGET_UID}/bus" \
      systemctl --user "$@"
  else
    log "未找到 ${TARGET_USER} 的 user systemd bus，跳过自动重启 mihomo。"
    log "请登录该用户后执行: systemctl --user restart ${SERVICE_NAME}"
  fi
}

restart_mihomo_if_possible() {
  if command -v systemctl >/dev/null 2>&1; then
    user_systemctl daemon-reload || true
    user_systemctl restart "$SERVICE_NAME" || true
  else
    log "未找到 systemctl，请手动重启 mihomo。"
  fi
}

enable_tun() {
  if [ ! -e /dev/net/tun ]; then
    log "警告: 未发现 /dev/net/tun，当前环境可能不支持 TUN。"
    if command -v modprobe >/dev/null 2>&1; then
      if [ "$(id -u)" -eq 0 ]; then
        modprobe tun || true
      elif command -v sudo >/dev/null 2>&1; then
        sudo modprobe tun || true
      fi
    fi
  fi

  backup_config
  set_tun_enabled true
  grant_mihomo_capability
  restart_mihomo_if_possible
}

disable_tun() {
  backup_config
  set_tun_enabled false
  restart_mihomo_if_possible
}

status_tun() {
  [ -f "$MIHOMO_CONFIG_FILE" ] || die "未找到 mihomo 配置: ${MIHOMO_CONFIG_FILE}"
  printf 'Target user: %s\n' "$TARGET_USER"
  printf 'Config: %s\n' "$MIHOMO_CONFIG_FILE"
  printf 'Binary: %s\n\n' "$MIHOMO_BIN"
  sed -n '/^tun:[[:space:]]*$/,/^[^[:space:]#][^:]*:[[:space:]]*/p' "$MIHOMO_CONFIG_FILE"
}

main() {
  local command="${1:-help}"

  case "$command" in
    enable) enable_tun ;;
    disable) disable_tun ;;
    status) status_tun ;;
    help | -h | --help) usage ;;
    *) usage; exit 1 ;;
  esac
}

main "$@"
